# Generated by Django 5.2.5 on 2025-08-08 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_web_contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
